---

- name: Build a Docker Image
  hosts: all
  gather_facts: no
  connection: local
  
  tasks:
    - name: create log folder
      file: 
        path: ../../../logs/
        state: directory

    - name: docker login (must `--no-include-email`)
      shell: "$(aws ecr get-login --region {{ aws.region }} --no-include-email)"
      args:
        executable: /bin/bash
      when: docker.repository.find('amazonaws.com') != -1 and image_type != 'base'
      
    - name: build image
      shell: "PACKER_LOG_PATH=logs/{{ docker.image.name }}-{{ image_type }}.log \
		                          PACKER_LOG=1 \
                              packer build \
                              -var 'version={{ docker.image.version }}' \
                              -var 'image_name={{ docker.image.name }}' \
                              -var 'repository={{ docker.repository }}' \
                              -var 'timezone={{ docker.timezone }}' \
                              templates/docker-{{ image_type }}.json"
      args:
        executable: /bin/bash
        chdir: "../../../"