---

- name: Publish a Docker Image to ECR
  hosts: all
  gather_facts: no
  connection: local
  
  tasks:
    - set_fact:
        post_fix: "{{ '' if (docker.image.name == 'base') else '-'+docker.image.name }}"

    - name: docker login (must `--no-include-email`)
      shell: "$(aws ecr get-login --region {{ aws.region }} --no-include-email)"
      args:
        executable: /bin/bash
      when: aws.region is search("amazonaws.com")

    - name: push image:version
      docker_image:
        name: "{{ docker.repository }}/{{ docker.image.name }}{{ post_fix }}"
        tag: "{{ docker.image.version }}"
        push: yes

    - name: publish image:latest
      docker_image:
        name: "{{ docker.repository }}/{{ docker.image.name }}{{ post_fix }}"
        tag: latest
        push: no